(ns dna-pipeline.router
  (:require [clojure.string :as str]
            [cheshire.core :as json]
            [dna-pipeline.parser :as parser]))

(defn route-record! [record]
  (if (= (:type record) :ok)
    (println "SAVING TO DB:" (pr-str (:payload record))) ;;1.True Branch
    (spit "error_dlq.json" (json/generate-string (:payload record))))) ;; 2. False Branch (The Else): Serialize data to JSON text and spit to disk

;; TEST HARNESS:

(def sample-error-map {:type :error :payload ["chr2" "20488" "." "G"]})

(route-record! sample-error-map)

(ns dna-pipeline.router
  (:require [clojure.string :as str]
            [cheshire.core :as json]
            [dna-pipeline.parser :as parser])) ;; Earlier created 

(defn  route-record! [record]
  (if (= (:type record) :ok)
    (println "SAVING TO DB:" (pr-str (:payload record)))
    (spit "error_dlq.json" (str (json/generate-string (:payload record)) "\n") :append true)))

;; The Integration Stream Runner
(defn ingest-vcf-stream! [lines]
  (run! route-record! (sequence parser/auditing-parser lines)))

;; TEST BLOCK:
(def heavy-mock-data
  ["#CHROM\tPOS\tID\tREF\tALT"
   "chr1\t10177\t.\tA\tAC"
   "   "
   "chr2\t20488\t.\tG"                        ;; Will route to JSON file
   "chr3\t30551\t.\tT\tTC"])

(ingest-vcf-stream! heavy-mock-data)

(ns dna-pipeline.router
  (:require [clojure.string :as str]
            [cheshire.core :as json]
            [dna-pipeline.parser :as parser]
            [clojure.java.io :as io])) ;; core I/O library

(defn route-record! [record]
  (if (= (:type record) :ok)
    (println "SAVING TO DB:" (pr-str (:payload record)))
    (spit "error_dlq.json" (str (json/generate-string (:payload record)) "\n") :append true)))

(defn ingest-vcf-stream! [lines]
  (run! route-record! (sequence parser/auditing-parser lines)))


(defn stream-vcf-file! [file-path]
  (with-open [rdr (io/reader file-path)]
    ;; Using ingest-vsf-stream! here on the lazy lines sequence generated by line-seq
    (ingest-vcf-stream! (line-seq rdr))))

(stream-vcf-file! "mock_data.vcf")
;; Try executing with the hidden .txt extension included:

(with-open [rdr (clojure.java.io/reader "mock_data.vcf")]
  (doall (take 3 (line-seq rdr))))

(sequence parser/auditing-parser ["chr1\t10177\t.\tA\tAC"])

;; Run this direct test in your Calva REPL to see the map fire:
(sequence parser/auditing-parser ["chr1 10177 . A AC"])



